### ISSUE TITLE
Rename stage0 stage1 and others

### ISSUE THREAD

**Issue by echeipesh** [geodocker/geodocker-jupyter-geopyspark#18]
`Dockerfile.stage0` -> `Dockerfile.build`
`Dockerfile.stage2` -> `Dockerfile`

`blobs` -> `artifacts`

`scripts/blob-*` -> `scripts/artifact-<a name>`

There should also be a writeup that explains the build process and motivations for `stage0` `stage2`.

MIA: `stage1`, have you seen it?

**Comment by jamesmcclain** [comment]
These names were carefully chosen in relation to a multi-stage bootstrap process.
