### ISSUE TITLE
Decouple geopyspark and geopyspark-netcdf versions

### ISSUE THREAD

**Issue by echeipesh** [geodocker/geodocker-jupyter-geopyspark#47]
The two do not iterate at the same rate and while we have not imposed the semver on these projects yet it would be much easier to iterate and test rather than bumping the geopyspark-netcdf version manually.

The deeper issue is that the way geopyspark-netcdf jars are being discovered during runtime are coupled to the geopyspark version.

**Comment by jamesmcclain** [comment]
See https://github.com/geotrellis/geopyspark-netcdf/issues/16

**Comment by jamesmcclain** [comment]
`geopyspark-netcdf` has been replaced with NetCDF and HDF5 (through rasterio and/or the GDAL Python bindings).
