### ISSUE TITLE
Recapture GDAL capabilities we lost with move away from native build

### ISSUE THREAD

**Issue by lossyrob** [geodocker/geodocker-jupyter-geopyspark#55]
This set of code:
```python
with rio.open('s3://mrgeo-source/srtm-v3-30/N00E006.hgt') as ds:
    bounds = ds.bounds
    height = ds.height
    width = ds.width
    crs = ds.get_crs()
    srs = osr.SpatialReference()
    srs.ImportFromWkt(crs.wkt)
    proj4 = srs.ExportToProj4()
    tile_cols = math.floor((width - 1) / 512) * 512
    tile_rows = math.floor((height - 1) / 512) * 512
    ws = [((x, x + 512), (y, y + 512)) for x in range(0,tile_cols, 512) \
                                          for y in range(0, tile_rows, 512)]
    print(bounds)
    print(height)
    print(width)
    print(crs)
    print(tile_cols)
    print(tile_rows)
    print(ws)
```

fails in the current container. In the `rde/workshop-prep` container, it succeeds.

I suspect this is due to the move away from a native GDAL build and towards a `pip` installed GDAL.

We should either figure out how to gain back those capabilities with the pip installed version, or move back to a native GDAL build.

**Comment by jamesmcclain** [comment]
What was the error message that was raised?

**Comment by lossyrob** [comment]
@jamesmcclain that the file could not be found. Generic GDAL message when it can't find a driver to read something, it falls through to the filesystem driver and says the file is not found. I didn't capture the exact error but I believe it would be the same as doing `gdalinfo /vsifoo/bar`

**Comment by jamesmcclain** [comment]
It is possible that there are some ancillary files that did not get packaged, I will check it out.
