### ISSUE TITLE
Username Password?

### ISSUE THREAD

**Issue by g07kore** [geodocker/geodocker-jupyter-geopyspark#82]
Hi, i know this is not really an issue but if i do  

`docker run -it --rm --name geopyspark \
   -p 8000:8000 -p 4040:4040 \
   quay.io/geodocker/jupyter-geopyspark`

why would you not explain whats the credentials? or how to get there?

**Comment by jamesmcclain** [comment]
The username and password are `hadoop` and `hadoop`.

**Comment by g07kore** [comment]
Thanks @jamesmcclain

**Comment by jamesmcclain** [comment]
You are welcome
