### ISSUE TITLE
Consider Dropping Support For Docker on EMR

### ISSUE THREAD

**Issue by jamesmcclain** [geodocker/geodocker-jupyter-geopyspark#89]
The original plan was to use the Docker image on EMR, but now that we have RPMs, it might be worthwhile to consider dropping support for using the Docker on EMR.  Doing that would simplify the image and reduce its size.

In particular, the `gdal-and-friends.tar.gz` binary blob could be dropped from the base image, and the two Python tarballs could be dropped from the main image.

**Comment by echeipesh** [comment]
I agree with this proposal. Aside from simplifying the image its worth pointing out that RPM deployment is easier to debug, where one does not have to keep track between the EMR native OS environment and the Docker OS environment. Now that we have gone through the trouble of building the RPMs dedicated to EMR deployment we should just standardize on those.

Docker image would still be useful for local testing and can install RPMs itself.

**Comment by jamesmcclain** [comment]
Closed by #90
